"""add used field to files table

Revision ID: 1918fb39c7f6
Revises: 0a0c9e115952
Create Date: 2024-05-04 14:10:41.980715

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "1918fb39c7f6"
down_revision: Union[str, None] = "0a0c9e115952"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column("used", sa.Boolean(), nullable=True, server_default="false"),
        schema="storage",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "used", schema="storage")
    # ### end Alembic commands ###
